#!/usr/bin/env bash
set -ex

cd solutions
for i in *.ipynb
do
jupyter nbconvert --to html --ExecutePreprocessor.allow_errors=True --ExecutePreprocessor.timeout=-1 --FilesWriter.build_directory=../../results --execute $i
done